package it.polimi.gc06.mesos.view.tui.visitors;

import it.polimi.gc06.mesos.model.cards.Card;
import it.polimi.gc06.mesos.model.cards.CardVisitor;
import it.polimi.gc06.mesos.model.cards.buildings.EndGameBuildingCard;
import it.polimi.gc06.mesos.model.cards.buildings.ModifierBuildingCard;
import it.polimi.gc06.mesos.model.cards.buildings.ObserverPairBuildingCard;
import it.polimi.gc06.mesos.model.cards.buildings.ObserverSetBuildingCard;

public class TuiBuildingEffectVisitor extends CardVisitor {

    private String effectText;

    public String getEffect(Card card) {
        this.effectText = "No special effect";
        card.accept(this);
        return effectText;
    }


    @Override
    public void visit(ObserverSetBuildingCard card) {
        effectText = "Grants +5 Food whenever you complete a Character Set (one of each type).";
    }

    @Override
    public void visit(ObserverPairBuildingCard card) {
        effectText = "Grants +2 Food whenever you complete a pair of Inventors.";
    }


    @Override
    public void visit(ModifierBuildingCard card) {
        if (card.getCardKey() == null) {
            effectText = "Unknown Modifier Effect.";
            return;
        }

        switch (card.getCardKey()) {
            case PICK_FROM_TOP:
                effectText = "Allows you to pick Buildings from the top row of the offer.";
                break;
            case TILE_FOOD_BONUS:
                effectText = "Increases the food received from the Turn Order Track slots.";
                break;
            case SUSTENANCE_GATHERER_DISCOUNT:
                effectText = "Reduces the food cost to maintain your Gatherers.";
                break;
            case SUSTENANCE_ARTIST_DISCOUNT:
                effectText = "Reduces the food cost to maintain your Artists.";
                break;
            case SUSTENANCE_INVENTOR_DISCOUNT:
                effectText = "Reduces the food cost to maintain your Inventors.";
                break;
            case RITUAL_NO_LOSS_CARD:
                effectText = "You suffer no penalties or losses upon defeat during the Ritual event.";
                break;
            case RITUAL_DOUBLE_WIN_CARD:
                effectText = "You gain double rewards upon victory during the Ritual event.";
                break;
            case RITUAL_THREE_STAR_CARD:
                effectText = "Adds +3 Stars to your strength during the Ritual event resolution.";
                break;
            case PAINTING_FOOD_GAIN_CARD:
                effectText = "Gain bonus Food during the Painting event resolution.";
                break;
            case HUNT_PRESTIGE_AND_FOOD_GAIN_CARD:
                effectText = "Gain extra Prestige and Food during the Hunt event resolution.";
                break;
            default:
                effectText = "Special effect: " + card.getCardKey().name();
                break;
        }
    }

    @Override
    public void visit(EndGameBuildingCard card) {
        if (card.getPrestigeEffect() == null) {
            effectText = "Grants prestige points at the end of the game.";
            return;
        }

        switch (card.getPrestigeEffect()) {
            case COUNT_ARTISTS:
                effectText = "End Game: +4 Prestige Points for each Artist you own.";
                break;
            case COUNT_BUILDERS:
                effectText = "End Game: +4 Prestige Points for each Builder you own.";
                break;
            case COUNT_GATHERERS:
                effectText = "End Game: +4 Prestige Points for each Gatherer you own.";
                break;
            case COUNT_HUNTERS:
                effectText = "End Game: +3 Prestige Points for each Hunter you own.";
                break;
            case COUNT_INVENTORS:
                effectText = "End Game: +2 Prestige Points for each Inventor you own.";
                break;
            case COUNT_SETS:
                effectText = "End Game: +6 Prestige Points for each complete Character Set you own.";
                break;
            case COUNT_SHAMANS:
                effectText = "End Game: +4 Prestige Points for each Shaman you own.";
                break;
            case DOUBLE_BUILDERS:
                effectText = "End Game: Doubles the Prestige Points generated by all your Builders.";
                break;
            case FIXED_25:
                effectText = "End Game: Gain exactly +25 Prestige Points.";
                break;
            default:
                effectText = "End Game prestige based on: " + card.getPrestigeEffect().name();
                break;
        }
    }
}